create table if not exists suggestions (
  id text primary key,
  title text not null,
  category text not null check (category in ('outdoors', 'culture', 'food', 'fitness', 'social', 'productive', 'creative', 'rest')),
  description text not null,
  location_label text not null,
  cost text not null check (cost in ('free', 'low', 'medium', 'high')),
  distance_miles numeric(6, 2) not null check (distance_miles >= 0),
  duration_hours numeric(5, 2) not null check (duration_hours > 0),
  energy text not null check (energy in ('low', 'medium', 'high')),
  social text not null check (social in ('solo', 'pair', 'group', 'flexible')),
  weather_fit text[] not null,
  tags text[] not null,
  source text not null check (source in ('event', 'city', 'everyday', 'productive')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists suggestions_active_source_idx
  on suggestions (active, source);

insert into suggestions (
  id,
  title,
  category,
  description,
  location_label,
  cost,
  distance_miles,
  duration_hours,
  energy,
  social,
  weather_fit,
  tags,
  source
) values
  (
    'park-walk',
    'Take a weather-matched park walk',
    'outdoors',
    'A relaxed loop through a nearby green space with a stop for coffee or tea.',
    'Nearest large park',
    'low',
    1.2,
    1.5,
    'medium',
    'flexible',
    array['clear', 'cloudy', 'cold'],
    array['fresh-air', 'low-planning', 'reset'],
    'city'
  ),
  (
    'museum-hour',
    'Visit one small exhibit',
    'culture',
    'Pick a single gallery or exhibit instead of trying to cover the whole museum.',
    'Downtown museum district',
    'medium',
    3.4,
    2,
    'low',
    'pair',
    array['rain', 'snow', 'hot', 'cold', 'cloudy'],
    array['art', 'indoors', 'date-friendly'],
    'event'
  ),
  (
    'deep-work-sprint',
    'Run a 90-minute deep work sprint',
    'productive',
    'Choose one meaningful task, set a timer, and close the loop with a short note.',
    'Home or a quiet cafe',
    'free',
    0.1,
    1.5,
    'medium',
    'solo',
    array['clear', 'cloudy', 'rain', 'snow', 'hot', 'cold'],
    array['focus', 'career', 'momentum'],
    'productive'
  ),
  (
    'new-lunch',
    'Try a lunch spot in a new neighborhood',
    'food',
    'Go somewhere close enough to be easy, but unfamiliar enough to make the day feel bigger.',
    'Nearby neighborhood strip',
    'medium',
    2.1,
    1.25,
    'low',
    'flexible',
    array['clear', 'cloudy', 'hot', 'cold'],
    array['food', 'explore', 'low-planning'],
    'city'
  ),
  (
    'friend-checkin',
    'Invite someone for a quick check-in',
    'social',
    'A short walk, call, or drink with someone you have been meaning to catch up with.',
    'Close to either person',
    'low',
    1.8,
    1,
    'medium',
    'pair',
    array['clear', 'cloudy', 'rain', 'snow', 'hot', 'cold'],
    array['connection', 'low-planning', 'evening'],
    'everyday'
  ),
  (
    'make-something',
    'Make one small creative thing',
    'creative',
    'Sketch, cook, write, remix a playlist, or photograph a small theme around you.',
    'Anywhere comfortable',
    'free',
    0,
    1,
    'low',
    'solo',
    array['clear', 'cloudy', 'rain', 'snow', 'hot', 'cold'],
    array['creative', 'indoors', 'reset'],
    'everyday'
  ),
  (
    'class-dropin',
    'Drop into a beginner-friendly class',
    'fitness',
    'Look for yoga, climbing, dance, or strength classes with a one-time pass.',
    'Local studio',
    'medium',
    4,
    1.25,
    'high',
    'group',
    array['rain', 'snow', 'cloudy', 'cold', 'hot'],
    array['movement', 'social', 'indoors'],
    'event'
  ),
  (
    'admin-reset',
    'Do a life admin reset',
    'productive',
    'Clear three tiny tasks: one bill, one message, and one calendar cleanup.',
    'Home',
    'free',
    0,
    0.75,
    'low',
    'solo',
    array['clear', 'cloudy', 'rain', 'snow', 'hot', 'cold'],
    array['chores', 'momentum', 'low-energy'],
    'productive'
  )
on conflict (id) do update set
  title = excluded.title,
  category = excluded.category,
  description = excluded.description,
  location_label = excluded.location_label,
  cost = excluded.cost,
  distance_miles = excluded.distance_miles,
  duration_hours = excluded.duration_hours,
  energy = excluded.energy,
  social = excluded.social,
  weather_fit = excluded.weather_fit,
  tags = excluded.tags,
  source = excluded.source,
  active = true,
  updated_at = now();
