import type { Suggestion } from "./types";

const allWeather = ["clear", "cloudy", "rain", "snow", "hot", "cold"] as const;
const indoorWeather = ["rain", "snow", "hot", "cold", "cloudy"] as const;
const outdoorWeather = ["clear", "cloudy", "cold"] as const;
const warmOutdoorWeather = ["clear", "cloudy", "hot"] as const;

export const demoSuggestions: Suggestion[] = [
  {
    id: "morning-coffee-walk",
    title: "Start with a coffee walk",
    category: "outdoors",
    description: "Pick up a drink and take a simple loop through a nearby street, park, or waterfront path.",
    locationLabel: "Nearby cafe and walking route",
    cost: "low",
    distanceMiles: 1,
    durationHours: 1,
    energy: "low",
    social: "flexible",
    weatherFit: ["clear", "cloudy", "cold"],
    tags: ["morning", "coffee", "fresh-air", "low-planning", "reset"],
    source: "city"
  },
  {
    id: "breakfast-counter",
    title: "Find a breakfast counter",
    category: "food",
    description: "Go somewhere casual for eggs, pastries, congee, or whatever breakfast looks like nearby.",
    locationLabel: "Neighborhood breakfast spot",
    cost: "low",
    distanceMiles: 1.5,
    durationHours: 1,
    energy: "low",
    social: "flexible",
    weatherFit: [...allWeather],
    tags: ["morning", "breakfast", "food", "low-planning"],
    source: "city"
  },
  {
    id: "library-morning-focus",
    title: "Do a quiet library focus block",
    category: "productive",
    description: "Bring one task to a library or calm public workspace and stop after one clean milestone.",
    locationLabel: "Public library or quiet workspace",
    cost: "free",
    distanceMiles: 2,
    durationHours: 2,
    energy: "medium",
    social: "solo",
    weatherFit: [...indoorWeather],
    tags: ["morning", "focus", "career", "indoors", "low-cost"],
    source: "productive"
  },
  {
    id: "fresh-air-errand-loop",
    title: "Turn errands into a fresh-air loop",
    category: "productive",
    description: "Bundle two small errands with a walk so the chore part feels less like dead time.",
    locationLabel: "Nearby shops and streets",
    cost: "low",
    distanceMiles: 1.8,
    durationHours: 1.5,
    energy: "medium",
    social: "solo",
    weatherFit: [...outdoorWeather],
    tags: ["morning", "afternoon", "chores", "fresh-air", "momentum"],
    source: "productive"
  },
  {
    id: "new-lunch",
    title: "Try a lunch spot in a new neighborhood",
    category: "food",
    description: "Go somewhere close enough to be easy, but unfamiliar enough to make the day feel bigger.",
    locationLabel: "Nearby neighborhood strip",
    cost: "medium",
    distanceMiles: 2.1,
    durationHours: 1.25,
    energy: "low",
    social: "flexible",
    weatherFit: ["clear", "cloudy", "hot", "cold"],
    tags: ["midday", "lunch", "food", "explore", "low-planning"],
    source: "city"
  },
  {
    id: "market-snack-browse",
    title: "Browse a market and pick one snack",
    category: "food",
    description: "Keep it light: wander a market, bakery row, or food hall and leave with one good find.",
    locationLabel: "Market, bakery strip, or food hall",
    cost: "low",
    distanceMiles: 2,
    durationHours: 1.5,
    energy: "medium",
    social: "flexible",
    weatherFit: [...allWeather],
    tags: ["midday", "lunch", "food", "explore", "low-planning"],
    source: "city"
  },
  {
    id: "park-picnic-hour",
    title: "Pack a simple park lunch",
    category: "outdoors",
    description: "Grab something portable and sit somewhere green without turning it into a whole expedition.",
    locationLabel: "Nearby park or plaza",
    cost: "low",
    distanceMiles: 1.4,
    durationHours: 1.25,
    energy: "low",
    social: "flexible",
    weatherFit: [...warmOutdoorWeather],
    tags: ["midday", "lunch", "fresh-air", "food", "reset"],
    source: "city"
  },
  {
    id: "gallery-before-dinner",
    title: "Visit one small exhibit",
    category: "culture",
    description: "Pick a single gallery, exhibit, or historic room instead of trying to cover everything.",
    locationLabel: "Museum or gallery district",
    cost: "medium",
    distanceMiles: 3.4,
    durationHours: 2,
    energy: "low",
    social: "pair",
    weatherFit: [...indoorWeather],
    tags: ["afternoon", "art", "indoors", "date-friendly"],
    source: "event"
  },
  {
    id: "bookstore-reset",
    title: "Do a bookstore reset",
    category: "rest",
    description: "Browse slowly, read a few first pages, and leave with either one book or one note to yourself.",
    locationLabel: "Bookstore or library branch",
    cost: "low",
    distanceMiles: 2,
    durationHours: 1.25,
    energy: "low",
    social: "solo",
    weatherFit: [...indoorWeather],
    tags: ["afternoon", "indoors", "reset", "low-energy"],
    source: "everyday"
  },
  {
    id: "neighborhood-photo-walk",
    title: "Take a neighborhood photo walk",
    category: "creative",
    description: "Pick a theme like signs, doors, shadows, or color and collect ten small observations.",
    locationLabel: "Interesting nearby streets",
    cost: "free",
    distanceMiles: 2,
    durationHours: 1.5,
    energy: "medium",
    social: "solo",
    weatherFit: [...outdoorWeather],
    tags: ["afternoon", "creative", "fresh-air", "explore"],
    source: "city"
  },
  {
    id: "waterfront-or-viewpoint",
    title: "Go find water or a good view",
    category: "outdoors",
    description: "Head toward a river, lake, bridge, overlook, hill, or skyline spot and stay just long enough to exhale.",
    locationLabel: "Waterfront, lookout, or scenic path",
    cost: "free",
    distanceMiles: 3,
    durationHours: 2,
    energy: "medium",
    social: "flexible",
    weatherFit: [...warmOutdoorWeather],
    tags: ["afternoon", "evening", "fresh-air", "reset", "touristy-but-worth-it"],
    source: "city"
  },
  {
    id: "rainy-day-cafe-read",
    title: "Hide out with a cafe read",
    category: "rest",
    description: "Bring a book, article, or saved essay to a comfortable indoor spot and give it your full attention.",
    locationLabel: "Cozy cafe or tea shop",
    cost: "low",
    distanceMiles: 1.5,
    durationHours: 1.5,
    energy: "low",
    social: "solo",
    weatherFit: ["rain", "snow", "cold", "cloudy"],
    tags: ["rainy-day", "indoors", "coffee", "reset", "low-energy"],
    source: "everyday"
  },
  {
    id: "hot-day-indoor-culture",
    title: "Duck into indoor culture",
    category: "culture",
    description: "Use the heat as an excuse for a museum, matinee, archive, aquarium, or public building you rarely visit.",
    locationLabel: "Air-conditioned cultural stop",
    cost: "medium",
    distanceMiles: 3,
    durationHours: 2,
    energy: "low",
    social: "flexible",
    weatherFit: ["hot", "rain", "snow"],
    tags: ["indoors", "art", "hot-day", "low-planning"],
    source: "event"
  },
  {
    id: "cold-day-noodle-bowl",
    title: "Warm up with noodles or soup",
    category: "food",
    description: "Find ramen, pho, stew, dumplings, or another warming meal that gives the day a center.",
    locationLabel: "Casual restaurant nearby",
    cost: "medium",
    distanceMiles: 2,
    durationHours: 1.25,
    energy: "low",
    social: "flexible",
    weatherFit: ["cold", "snow", "rain"],
    tags: ["lunch", "dinner", "food", "cold-day", "low-planning"],
    source: "city"
  },
  {
    id: "after-work-drink-or-dessert",
    title: "Meet for a drink or dessert",
    category: "social",
    description: "Make it easy to say yes: one place, one hour, and a low-pressure reason to catch up.",
    locationLabel: "Bar, cafe, or dessert spot",
    cost: "medium",
    distanceMiles: 2,
    durationHours: 1.25,
    energy: "medium",
    social: "pair",
    weatherFit: [...allWeather],
    tags: ["evening", "drinks", "connection", "date-friendly"],
    source: "everyday"
  },
  {
    id: "dinner-near-a-walk",
    title: "Pair dinner with a short walk",
    category: "food",
    description: "Choose dinner near a pleasant block, river path, main street, or plaza so the plan has a second act.",
    locationLabel: "Restaurant near a walkable area",
    cost: "medium",
    distanceMiles: 2.5,
    durationHours: 2,
    energy: "medium",
    social: "flexible",
    weatherFit: ["clear", "cloudy", "cold", "hot"],
    tags: ["evening", "dinner", "food", "fresh-air", "date-friendly"],
    source: "city"
  },
  {
    id: "free-community-event",
    title: "Look for a free community event",
    category: "social",
    description: "Check for a library talk, open mic, meetup, board-game night, gallery opening, or neighborhood festival.",
    locationLabel: "Community venue",
    cost: "free",
    distanceMiles: 4,
    durationHours: 2,
    energy: "medium",
    social: "group",
    weatherFit: [...allWeather],
    tags: ["evening", "connection", "low-cost", "social"],
    source: "event"
  },
  {
    id: "beginner-class-dropin",
    title: "Drop into a beginner-friendly class",
    category: "fitness",
    description: "Look for yoga, climbing, dance, boxing, pottery, language, or cooking classes with a one-time pass.",
    locationLabel: "Local studio or class space",
    cost: "medium",
    distanceMiles: 4,
    durationHours: 1.25,
    energy: "high",
    social: "group",
    weatherFit: [...indoorWeather],
    tags: ["evening", "movement", "social", "indoors"],
    source: "event"
  },
  {
    id: "gentle-gym-or-swim",
    title: "Choose a gentle gym or swim session",
    category: "fitness",
    description: "Do the version that leaves you better afterward: light weights, a swim, stretching, or an easy bike.",
    locationLabel: "Gym, pool, or community center",
    cost: "low",
    distanceMiles: 2.5,
    durationHours: 1.25,
    energy: "medium",
    social: "solo",
    weatherFit: [...allWeather],
    tags: ["morning", "evening", "movement", "reset"],
    source: "everyday"
  },
  {
    id: "deep-work-sprint",
    title: "Run a 90-minute deep work sprint",
    category: "productive",
    description: "Choose one meaningful task, set a timer, and close the loop with a short note.",
    locationLabel: "Home, library, or quiet cafe",
    cost: "free",
    distanceMiles: 0.1,
    durationHours: 1.5,
    energy: "medium",
    social: "solo",
    weatherFit: [...allWeather],
    tags: ["morning", "afternoon", "focus", "career", "momentum"],
    source: "productive"
  },
  {
    id: "admin-reset",
    title: "Do a life admin reset",
    category: "productive",
    description: "Clear three tiny tasks: one bill, one message, and one calendar cleanup.",
    locationLabel: "Home",
    cost: "free",
    distanceMiles: 0,
    durationHours: 0.75,
    energy: "low",
    social: "solo",
    weatherFit: [...allWeather],
    tags: ["chores", "momentum", "low-energy"],
    source: "productive"
  },
  {
    id: "home-reset-hour",
    title: "Reset one corner of home",
    category: "rest",
    description: "Pick the smallest visible area, put on music, and make it feel noticeably calmer in under an hour.",
    locationLabel: "Home",
    cost: "free",
    distanceMiles: 0,
    durationHours: 1,
    energy: "low",
    social: "solo",
    weatherFit: [...allWeather],
    tags: ["chores", "reset", "low-energy", "indoors"],
    source: "everyday"
  },
  {
    id: "make-something",
    title: "Make one small creative thing",
    category: "creative",
    description: "Sketch, cook, write, remix a playlist, mend something, or photograph a small theme around you.",
    locationLabel: "Anywhere comfortable",
    cost: "free",
    distanceMiles: 0,
    durationHours: 1,
    energy: "low",
    social: "solo",
    weatherFit: [...allWeather],
    tags: ["creative", "indoors", "reset"],
    source: "everyday"
  },
  {
    id: "cook-one-good-meal",
    title: "Cook one good meal",
    category: "creative",
    description: "Choose a recipe simple enough to finish and interesting enough to make dinner feel intentional.",
    locationLabel: "Home kitchen",
    cost: "low",
    distanceMiles: 0,
    durationHours: 1.5,
    energy: "medium",
    social: "flexible",
    weatherFit: [...allWeather],
    tags: ["evening", "dinner", "creative", "food", "indoors"],
    source: "everyday"
  },
  {
    id: "solo-movie-matinee",
    title: "Take yourself to a matinee",
    category: "culture",
    description: "Pick the showing that starts soonest and let the plan be easy instead of optimal.",
    locationLabel: "Cinema or repertory theater",
    cost: "medium",
    distanceMiles: 3,
    durationHours: 2.5,
    energy: "low",
    social: "solo",
    weatherFit: [...indoorWeather],
    tags: ["afternoon", "indoors", "art", "low-planning"],
    source: "event"
  },
  {
    id: "long-city-wander",
    title: "Spend the day on a city wander",
    category: "outdoors",
    description: "Choose two anchors, like a park and a food stop, then let the route between them be the point.",
    locationLabel: "Two walkable neighborhoods",
    cost: "medium",
    distanceMiles: 5,
    durationHours: 5,
    energy: "medium",
    social: "flexible",
    weatherFit: [...warmOutdoorWeather],
    tags: ["all-day", "explore", "fresh-air", "food", "touristy-but-worth-it"],
    source: "city"
  },
  {
    id: "transit-adventure",
    title: "Ride transit to a new pocket of the city",
    category: "culture",
    description: "Pick a station or stop you rarely use, walk around for an hour, and find one local place worth remembering.",
    locationLabel: "Transit-accessible neighborhood",
    cost: "low",
    distanceMiles: 6,
    durationHours: 3,
    energy: "medium",
    social: "flexible",
    weatherFit: ["clear", "cloudy", "cold", "hot"],
    tags: ["all-day", "afternoon", "explore", "low-cost"],
    source: "city"
  },
  {
    id: "two-stop-cultural-day",
    title: "Make a two-stop culture day",
    category: "culture",
    description: "Pair a museum, gallery, film, or historic site with a nearby food stop so it feels like a real outing.",
    locationLabel: "Cultural district",
    cost: "medium",
    distanceMiles: 4,
    durationHours: 4,
    energy: "medium",
    social: "pair",
    weatherFit: [...indoorWeather],
    tags: ["all-day", "art", "food", "indoors", "date-friendly"],
    source: "event"
  },
  {
    id: "volunteer-shift",
    title: "Look for a short volunteer shift",
    category: "social",
    description: "Search for a food bank, cleanup, community garden, mutual-aid, or event-support shift with a clear start time.",
    locationLabel: "Community organization",
    cost: "free",
    distanceMiles: 5,
    durationHours: 3,
    energy: "medium",
    social: "group",
    weatherFit: [...allWeather],
    tags: ["connection", "low-cost", "social", "meaningful"],
    source: "event"
  },
  {
    id: "friend-checkin",
    title: "Invite someone for a quick check-in",
    category: "social",
    description: "A short walk, call, or drink with someone you have been meaning to catch up with.",
    locationLabel: "Close to either person",
    cost: "low",
    distanceMiles: 1.8,
    durationHours: 1,
    energy: "medium",
    social: "pair",
    weatherFit: [...allWeather],
    tags: ["connection", "low-planning", "evening"],
    source: "everyday"
  },
  {
    id: "phone-call-walk",
    title: "Take a phone-call walk",
    category: "social",
    description: "Call someone while walking a familiar route, then stop when the loop ends.",
    locationLabel: "Familiar walking route",
    cost: "free",
    distanceMiles: 1.5,
    durationHours: 1,
    energy: "medium",
    social: "pair",
    weatherFit: [...outdoorWeather],
    tags: ["connection", "fresh-air", "low-cost", "low-planning"],
    source: "everyday"
  },
  {
    id: "late-night-wind-down",
    title: "Do a late-night wind-down",
    category: "rest",
    description: "Keep it small: shower, tea, dim lights, one page or one playlist, and no heroic productivity.",
    locationLabel: "Home",
    cost: "free",
    distanceMiles: 0,
    durationHours: 0.75,
    energy: "low",
    social: "solo",
    weatherFit: [...allWeather],
    tags: ["night", "wind-down", "reset", "low-energy"],
    source: "everyday"
  },
  {
    id: "plan-tomorrow-lightly",
    title: "Lightly set up tomorrow",
    category: "productive",
    description: "Write tomorrow's first three moves, put one thing by the door, and stop before it becomes a project.",
    locationLabel: "Home",
    cost: "free",
    distanceMiles: 0,
    durationHours: 0.5,
    energy: "low",
    social: "solo",
    weatherFit: [...allWeather],
    tags: ["night", "focus", "low-energy", "momentum"],
    source: "productive"
  }
];
