import type { Suggestion } from "./types";

export const demoSuggestions: Suggestion[] = [
  {
    id: "park-walk",
    title: "Take a weather-matched park walk",
    category: "outdoors",
    description: "A relaxed loop through a nearby green space with a stop for coffee or tea.",
    locationLabel: "Nearest large park",
    cost: "low",
    distanceMiles: 1.2,
    durationHours: 1.5,
    energy: "medium",
    social: "flexible",
    weatherFit: ["clear", "cloudy", "cold"],
    tags: ["fresh-air", "low-planning", "reset"],
    source: "city"
  },
  {
    id: "museum-hour",
    title: "Visit one small exhibit",
    category: "culture",
    description: "Pick a single gallery or exhibit instead of trying to cover the whole museum.",
    locationLabel: "Downtown museum district",
    cost: "medium",
    distanceMiles: 3.4,
    durationHours: 2,
    energy: "low",
    social: "pair",
    weatherFit: ["rain", "snow", "hot", "cold", "cloudy"],
    tags: ["art", "indoors", "date-friendly"],
    source: "event"
  },
  {
    id: "deep-work-sprint",
    title: "Run a 90-minute deep work sprint",
    category: "productive",
    description: "Choose one meaningful task, set a timer, and close the loop with a short note.",
    locationLabel: "Home or a quiet cafe",
    cost: "free",
    distanceMiles: 0.1,
    durationHours: 1.5,
    energy: "medium",
    social: "solo",
    weatherFit: ["clear", "cloudy", "rain", "snow", "hot", "cold"],
    tags: ["focus", "career", "momentum"],
    source: "productive"
  },
  {
    id: "new-lunch",
    title: "Try a lunch spot in a new neighborhood",
    category: "food",
    description: "Go somewhere close enough to be easy, but unfamiliar enough to make the day feel bigger.",
    locationLabel: "Nearby neighborhood strip",
    cost: "medium",
    distanceMiles: 2.1,
    durationHours: 1.25,
    energy: "low",
    social: "flexible",
    weatherFit: ["clear", "cloudy", "hot", "cold"],
    tags: ["food", "explore", "low-planning"],
    source: "city"
  },
  {
    id: "friend-checkin",
    title: "Invite someone for a quick check-in",
    category: "social",
    description: "A short walk, call, or drink with someone you have been meaning to catch up with.",
    locationLabel: "Close to either person",
    cost: "low",
    distanceMiles: 1.8,
    durationHours: 1,
    energy: "medium",
    social: "pair",
    weatherFit: ["clear", "cloudy", "rain", "snow", "hot", "cold"],
    tags: ["connection", "low-planning", "evening"],
    source: "everyday"
  },
  {
    id: "make-something",
    title: "Make one small creative thing",
    category: "creative",
    description: "Sketch, cook, write, remix a playlist, or photograph a small theme around you.",
    locationLabel: "Anywhere comfortable",
    cost: "free",
    distanceMiles: 0,
    durationHours: 1,
    energy: "low",
    social: "solo",
    weatherFit: ["clear", "cloudy", "rain", "snow", "hot", "cold"],
    tags: ["creative", "indoors", "reset"],
    source: "everyday"
  },
  {
    id: "class-dropin",
    title: "Drop into a beginner-friendly class",
    category: "fitness",
    description: "Look for yoga, climbing, dance, or strength classes with a one-time pass.",
    locationLabel: "Local studio",
    cost: "medium",
    distanceMiles: 4,
    durationHours: 1.25,
    energy: "high",
    social: "group",
    weatherFit: ["rain", "snow", "cloudy", "cold", "hot"],
    tags: ["movement", "social", "indoors"],
    source: "event"
  },
  {
    id: "admin-reset",
    title: "Do a life admin reset",
    category: "productive",
    description: "Clear three tiny tasks: one bill, one message, and one calendar cleanup.",
    locationLabel: "Home",
    cost: "free",
    distanceMiles: 0,
    durationHours: 0.75,
    energy: "low",
    social: "solo",
    weatherFit: ["clear", "cloudy", "rain", "snow", "hot", "cold"],
    tags: ["chores", "momentum", "low-energy"],
    source: "productive"
  }
];
